# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:      pretty
baseurl: 	    	/2025sp-GenAI-overview/
url:            https://qiyanjun.github.io/

# Setup
title:            	"2025 Spring UVA CS - GenAI-Overview"
tagline:          	"2025 Spring"
description:        "Graduate and Senior Under Level Seminar"
future: 			true

author:
  name:           'Dr. Yanjun Qi'
  url:            https://www.yanjunqi.org/


remote_theme: mmistakes/minimal-mistakes@4.24.0

collections:
  contents:
    sort_by: LOrder
    output: true

plugins: 
  - jekyll-include-cache
